FROM continuumio/miniconda3:4.5.12

# utils
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

RUN conda install gxx_linux-64

RUN conda install python=3.6

RUN apt-get install -y --force-yes default-libmysqlclient-dev mysql-client build-essential

# Grab requirements.txt.
COPY requirementssenti.txt /tmp/requirementssenti.txt

# Install dependencies
RUN pip install -qr /tmp/requirementssenti.txt

# create a user for web server
RUN adduser --disabled-password --gecos "" foo

COPY ./ /opt/src

WORKDIR /opt/src
